
var emp = [{
    name: "Aji",
    age: 21,
    location: "dgl",
    vehicle: "dio",
    gender: "M",
    position: "Developer",
    doj:01-12-2018,
    
},
{
    name: "karthiga",
    age: 24,
    domain: "js",
    location: "svg",
    vehicle: "dio",
    gender: "F",
    position: "Developer",
    doj:02-12-2018,
},
{
    name: "sangami",
    age: 20,
    domain: "js",
    location: "mdu",
    vehicle: "fz",
    gender: "F",
    position: "Developer",
    doj:03-12-2018,
},
{
    name: "shanmugam",
    age: 22,
    domain: "php",
    location: "mdu",
    vehicle: "car",
    gender: "M",
    position: "Teamlead",
    doj:04-12-2018,
},
{
    name: "yogesh",
    age: 22,
    domain: "js",
    location: "svg",
    vehicle: "fz",
    gender: "M",
    position: "Teamlead",
    doj:05-12-2018,
},
{
    name: "bala",
    age: 21,
    domain: "php",
    location: "svg",
    vehicle: "car",
    gender: "M",
    position: "Projmanager",
    doj:06-12-2018,
},
{
    name: "venkat",
    age: 20,
    domain: "ios",
    location: "mdu",
    vehicle: "fz",
    gender: "M",
    position: "Projmanager",
    doj:07-12-2018,
},
{
    name: "akash",
    age: 21,
    location: "dgl",
    vehicle: "dio",
    gender: "M",
    position: "Developer",
    doj:08-12-2018,
},
{
    name: "ajay",
    age: 24,
    domain: "js",
    location: "svg",
    vehicle: "dio",
    gender: "M",
    position: "Developer",
    doj:09-12-2018,
},
{
    name: "kishore",
    age: 20,
    domain: "js",
    location: "mdu",
    vehicle: "fz",
    gender: "M",
    position: "Developer",
    doj:10-12-2018,
},
{
    name: "mathan",
    age: 22,
    domain: "php",
    location: "mdu",
    vehicle: "car",
    gender: "M",
    position: "Teamlead",
    doj:11-12-2018,
},
{
    name: "yogeshwaran",
    age: 22,
    domain: "js",
    location: "svg",
    vehicle: "fz",
    gender: "M",
    position: "Teamlead",
    doj:12-12-2018,
},
{
    name: "sakthi",
    age: 21,
    domain: "php",
    location: "svg",
    vehicle: "car",
    gender: "M",
    position: "Projmanager",
    doj:13-12-2018,
},
{
    name: "krisnan",
    age: 20,
    domain: "ios",
    location: "mdu",
    vehicle: "fz",
    gender: "M",
    position: "Projmanager",
    doj:14-12-2018,
}
];
<body>
    <p id="demo"></p>
    <script>
        function filterAge(){
           for(var i=0;i<index.length;)
    </script>

    
</body>